import { CameraApiResponse } from "@/app/types/camera";

export const mockCamerasResponse: CameraApiResponse[] = [
  {
    id: "cam-1",
    cameraName: "Main Entrance",
    cameraIp: "192.168.1.10",
    userName: "admin",
    password: "••••••••",
    RTSPport: 554,
    cameraZone: "Perimeter",
    cameraLocation: "Main Gate",
    connectionType: "DIRECT_TO_CAMERA",
    rtspStream: "rtsp://192.168.1.10/stream",
  },
  {
    id: "cam-2",
    cameraName: "Assembly Line 1",
    cameraIp: "192.168.1.11",
    userName: "admin",
    password: "••••••••",
    RTSPport: 554,
    cameraZone: "Manufacturing Floor",
    cameraLocation: "Assembly Line 1",
    connectionType: "NVR",
    rtspStream: "rtsp://192.168.1.11/stream",
  },
  {
    id: "cam-3",
    cameraName: "Loading Dock",
    cameraIp: "192.168.1.12",
    userName: "admin",
    password: "••••••••",
    RTSPport: 554,
    cameraZone: "Warehouse",
    cameraLocation: "Loading Dock",
    connectionType: "DIRECT_TO_CAMERA",
    rtspStream: "rtsp://192.168.1.12/stream",
  },
  {
    id: "cam-4",
    cameraName: "Main Gate",
    cameraIp: "192.168.1.13",
    userName: "admin",
    password: "••••••••",
    RTSPport: 554,
    cameraZone: "Perimeter",
    cameraLocation: "Main Gate",
    connectionType: "NVR",
    rtspStream: "rtsp://192.168.1.13/stream",
  },
  {
    id: "cam-5",
    cameraName: "Canteen",
    cameraIp: "192.168.1.14",
    userName: "admin",
    password: "••••••••",
    RTSPport: 554,
    cameraZone: "Office Block",
    cameraLocation: "Canteen",
    connectionType: "DIRECT_TO_CAMERA",
    rtspStream: "rtsp://192.168.1.14/stream",
  },
];
