export const FEATURE = {
  // Dashboards
  SAFETY_COMPLIANCE: "SF001",
  SURVEILLANCE_MONITORING: "SF002",
  OPERATIONAL_INSIGHTS: "SF003",
  WORKFORCE_MONITORING: "SF004",

  // Alerts
  ALERTS: "SF005",

  // Settings
  ROLE_MANAGEMENT: "SF006",
  USER_MANAGEMENT: "SF007",

  // Configurator
  CAMERA_MANAGEMENT: "SF017",
  USE_CASE_MANAGER: "SF015",
  ZONE_LOCATION_MAPPING: "SF016",

  // Analytics – Safety & Compliance
  PPE_DETECTION: "SUC001",
  FIRE_SMOKE: "SUC002",
  FALL_DETECTION: "SUC003",
  OBJECT_DETECTION: "SUC004",
  EMERGENCY_EXIT_BLOCKAGE: "SUC005",
  CROWD_DETECTION: "SUC006",

  // Surveillance Monitoring
  INTRUSION_DETECTION: "SUC007",
  UNAUTHORIZED_ACCESS: "SUC008",
  CAMERA_TAMPERING: "SUC009",
  MOVEMENT_DURING_SHUTDOWN_HOUR: "SUC010",

  // Workforce Monitoring
  EMPLOYEE_PRESENCE_CRITICAL_AREA: "SUC011",
  EMPLOYEE_PRESENCE_RESTRICTED_AREA: "SUC012",
  EMPLOYEE_IDLE_TIME: "SUC013",
  MOBILE_PHONE_USAGE: "SUC014",
  SLEEPING_SECURITY_PERSONNEL: "SUC015",

  // Operational Insight
  PEOPLE_COUNT: "SUC016",
  VEHICLE_COUNT: "SUC017",
  CANTEEN_USAGE: "SUC018",
  VEHICLE_UNLOADING_LOADING: "SUC019",
  UNAUTHORIZED_PARKING: "SUC020",

  // Face Recognition
  FACE_RECOGNITION: "SUC021",
  FACE_IDLE_MONITORING: "SUC022",

  // Live Streaming
  LIVE_STREAMING: "SF009",

  // Permissions FOR ROLE
  CREATE_ROLE: "SF018",
  VIEW_ROLE: "SF019",
  DELETE_ROLE: "SF020",
  EDIT_ROLE: "SF021",

  //PERMISSIONS FOR USER
  ADD_USER: "SF010",
  EDIT_USER: "SF011",
  DELETE_USER: "SF012",
  VIEW_USER: "SF013",
} as const;

export type FeatureId = (typeof FEATURE)[keyof typeof FEATURE];
